[build]
  command = "npm install && npx vite build --config vite.config.production.ts"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_MODE = "production"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
